import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hiba's portfolio</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <ul className={styles.socialmedia}>
          <li>
            <a
              href="https://www.linkedin.com/in/hiba-abdel-karim/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Linkedin
            </a>
          </li>

          <li>
            <a
              href="https://twitter.com/abdelkarim_hiba"
              target="_blank"
              rel="noopener noreferrer"
            >
              Twitter
            </a>
          </li>

          <li>
            <a
              href="https://github.com/harkibit"
              target="_blank"
              rel="noopener noreferrer"
            >
              Github
            </a>
          </li>

          <li>
            <a
              href="https://stackoverflow.com/users/15598509/hiba-abdel-karim"
              target="_blank"
              rel="noopener noreferrer"
            >
              StackOverflow
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
}
